### ISSUE TITLE
"this doesn't seem right" :smile: 

### ISSUE THREAD

**Issue by decentral1se** [ssbc/.github#3]
> Notice: regular should be made a member (trustnet 4.1 >= 4 and last active 11 months ago)
> Notice: mycognosist should be removed (trustnet 3.8 < 4)
> Error: 2 actions need to be done

**Comment by staltz** [comment]
Yeah I know CI is telling me to remove @mycognosist but I don't feel like doing that. :sweat_smile: Our process (explained in a n SSB thread) is that these calculations inform us what to do but we don't need to blindly follow them. I disagree with the calculation this time because it seems like the trustnet score is gradually going down over time (not just for mycognosist, but for lots of other people, including me and arj and mix) and this doesn't seem right.

I believe soon enough the algorithm will tell us to add you, decentral1se. :)

**Comment by decentral1se** [comment]
Haha, right! Title updated to reflect algorithmic suspicion :upside_down_face:

**Comment by cblgh** [comment]
i wonder if it would be any different if you used the built-in breaks? on ssb i wrote about an experiment i did where i reimplemented what you're doing with the manual threshold, @staltz, but using the built-in mechanism of breaks and clustering. can't find that post while looking around tho cause patchwork's search is ass X)

with trustnet, the numeric score doesn't necessarily matter, so much as the final clusterings. e.g. you're using a fixed threshold (4) while the rankings are dynamically changing over time. how things are clustered depends on the differences in scores, thus the question about trying the built-in system of breaks, potentially tweaking things a bit with e.g. 4 breaks instead or something of that kind

some other things top of mind: 
* the metric used atm is probably naive if it's purely that a pr was merged without taking into account e.g. size of PR or type of repo? in other words: the trust weights are uniform for actions that might not be uniform. 
* also curious to see what would happen if there were different trust roots, e.g. arj or staltz and compare that with dominic. 
* as noted this underlying point that people in the graph are _competing_ for energy is definitely the weakpoint of trustnet as it is today! it's basically a fundamental flaw that comes from how the graph is evaluated with appleseed. the flaw doesn't matter as much in a moderation context since direct trust assignments from the root are implicitly included in the final trusted group e.g. me trusting A, B, C => A, B, C guaranteed to be trusted in final output

anyway it's interesting to see real life data coming of it in a non-moderation setting :)

**Comment by cblgh** [comment]
oh and two more cents:

the strategy of using a clustering algorithm to split the rankings into different groups (3, as of writing) was only ever intended to be _one_ strategy trustnet could use in refining the final set of rankings into a final group of trusted peers :> it happens to be a great fit for the subjective moderation context, where you know who you are trusting directly and don't mind getting in some recommendations from those peers according to how much they are trusted. 

in this more uniform and widespread graph, perhaps something else makes more sense! i have a feeling, after [looking at the numbers](https://github.com/ssbc/.github/actions/runs/3358134766/jobs/5564675691), that using perhaps 5-6 breaks of the clustering group would be enough to exclude very low trust-ranked contributors while lessening the inherent competitive dynamic of appleseed's energy propagation

**Comment by staltz** [comment]
@cblgh what are "breaks"?

**Comment by cblgh** [comment]
@staltz what i call it when you break the computed rankings into different clusters; breaking something continuous into smaller pieces (e.g. an uncooked noodle, crispbread, what have you): https://github.com/cblgh/trustnet/blob/master/trustnet.js#L70
